apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
  labels:
    app: hellok8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - name: hellok8s
        image: optimodev/hellok8s:v1
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
